### ISSUE TITLE
Add option to print variable values and messages

### ISSUE THREAD

**Issue by kangasta** [kangasta/yaml_requests#28]

**Comment by rotty3000** [comment]
@kangasta would you expect this to expand the jinja2 templates in variables or present them raw?

**Comment by kangasta** [comment]
Initially I though resolved values would be enough, but after seeing the raw form in your PR that seems useful as well 👍

Maybe it could have both, e.g __VariableWithTemplate__: {{ base_url }}/path → http://localhost:8080/path. This would need some logic to check if value is different after resolving templates to only show template for templated variables, but it should be quite simple to check.

**Comment by rotty3000** [comment]
Sounds fair, I will work on this change.

**Comment by rotty3000** [comment]
hey @kangasta as it turns out, the variables were not even template processed. Should I consider that a bug?

**Comment by rotty3000** [comment]
I am also experiencing an issue with jinja2 trying to parse a template in the variables.

consider the following:
```yaml
variables:
  dyn: "{{ 20 % 7 }}"
requests:
- get:
    url: https://google.com
  output:
  - variables
```
I am getting the following error:
```
]$ yaml_requests tst/plans/output-variables.yml 
ERROR: Caught unexpected error, see traceback and description below. If this seems like a bug to you, please consider creating a issue in https://github.com/kangasta/yaml_requests/issues.

Traceback (most recent call last):
  File "/home/me/projects/yaml_requests/.venv/lib/python3.11/site-packages/yaml_requests/_main.py", line 60, in main
    num_errors = run(args.plan_file, logger, variables_override)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/projects/yaml_requests/.venv/lib/python3.11/site-packages/yaml_requests/_main.py", line 94, in run
    runner = PlanRunner(plan, logger)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/projects/yaml_requests/.venv/lib/python3.11/site-packages/yaml_requests/_runner.py", line 14, in __init__
    for name, value in self._env.resolve_templates(self._plan.variables).items():
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/projects/yaml_requests/.venv/lib/python3.11/site-packages/yaml_requests/utils/template.py", line 69, in resolve_templates
    return self._resolve_dict(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/projects/yaml_requests/.venv/lib/python3.11/site-packages/yaml_requests/utils/template.py", line 57, in _resolve_dict
    return {key: self.resolve_templates(value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/projects/yaml_requests/.venv/lib/python3.11/site-packages/yaml_requests/utils/template.py", line 57, in <dictcomp>
    return {key: self.resolve_templates(value)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/projects/yaml_requests/.venv/lib/python3.11/site-packages/yaml_requests/utils/template.py", line 65, in resolve_templates
    return self._resolve_string(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/projects/yaml_requests/.venv/lib/python3.11/site-packages/yaml_requests/utils/template.py", line 46, in _resolve_string
    rendered = template.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/me/projects/yaml_requests/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/me/projects/yaml_requests/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
TypeError: unsupported operand type(s) for %: 'int' and 'str'
```
Without a template there is no error.

Any insight would be useful. While google has explained this error to me, I feel that jinja2 must not be parsing the template properly.

**Comment by rotty3000** [comment]
Ok, with a little debugging the problem lies in when adding the `| to_json` filter.

**Comment by rotty3000** [comment]
After further testing, there was just a bug in the variables templates (templates in variables were simply not processed). Also, I think after realizing that it no longer makes sense to attempt to show the "raw" values since getting those is really annoying considering when they are rendered.

**Comment by kangasta** [comment]
Thanks for the implementation! Support for templated variables is also a nice new feature. I'll try to take a look at the PR early next week and let's get that merged as well.
